services:
  backend:
    build: ./backend
    container_name: backend-test-container

    ports:
      - "8000:80"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL} 
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - CORS_ORIGINS=${CORS_ORIGINS}
    networks:
      - app-test-network
    volumes:
      - ./backend:/app 

  db:
    image: postgres:14
    container_name: postgres-test-container

    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: morie123
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:

      - app-test-network

  redis:
    image: redis:7
    container_name: redis-test-container
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-test-network 

networks:
  app-test-network:

volumes:
  db_data:
