

services:
  backend:
    build: ./backend
    container_name: backend-container
    ports:
      - "8000:80"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL} 
    networks:
      - app-network
    volumes:
      - ./backend:/app 

  db:
    image: postgres:14
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: morie123
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:

volumes:
  db_data:
