"""Added columns to vaultentry table

Revision ID: 07c7c95a403a
Revises: dbf6e04e220c
Create Date: 2025-03-11 06:10:13.604027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07c7c95a403a'
down_revision: Union[str, None] = 'dbf6e04e220c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vault_entries', sa.Column('last_modified_by', sa.String(), nullable=True))
    op.add_column('vault_entries', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('vault_entries', sa.Column('version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vault_entries', 'version')
    op.drop_column('vault_entries', 'deleted')
    op.drop_column('vault_entries', 'last_modified_by')
    # ### end Alembic commands ###
