"""changed nullable value for encryption key to true

Revision ID: 3f1b89079462
Revises: f6d70f017f7e
Create Date: 2025-03-06 20:02:53.398790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f1b89079462'
down_revision: Union[str, None] = 'f6d70f017f7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'encryption_key',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'encryption_key',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    # ### end Alembic commands ###
