"""Changed SHaredUserCreate user_id entry to user_email for consistency

Revision ID: dbf6e04e220c
Revises: fe263e110e1b
Create Date: 2025-03-07 07:49:57.220744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbf6e04e220c'
down_revision: Union[str, None] = 'fe263e110e1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
