"""Added delete on cascade, changed encrypted_password field to string 

Revision ID: eecae0ec7bd8
Revises: b7c2297b2bc7
Create Date: 2025-03-11 16:22:18.644401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eecae0ec7bd8'
down_revision: Union[str, None] = 'b7c2297b2bc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vault_entries', 'encrypted_password',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_unique_constraint('_user_site_uc', 'vault_entries', ['user_email', 'site'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_site_uc', 'vault_entries', type_='unique')
    op.alter_column('vault_entries', 'encrypted_password',
               existing_type=sa.String(),
               type_=postgresql.BYTEA(),
               existing_nullable=True)
    # ### end Alembic commands ###
